### ISSUE TITLE
感觉znet/connection 没有必要分两个channel来给客户端发送消息

### ISSUE THREAD

**Issue by hellodudu** [aceld/zinx#10]

**Comment by hellodudu** [comment]
应该没有什么业务场景是需要分不带缓冲的消息和带缓冲的消息吧，就算分的话，sendmsg的时候直接con.Write就行了，再传一遍channel有点费。

**Comment by hellodudu** [comment]
抱歉，手抖关了又开。

**Comment by aceld** [comment]
你说的是下图中，那个reader和writer之间的那个channel么？
![zinx读写分离模型](https://aceld.gitbooks.io/zinx/content/assets/3-Zinx-V0.7%E6%9E%B6%E6%9E%84%E6%A8%A1%E5%9E%8B.jpeg)

这个channel实际上是为了将业务进行分离用的，就是reader可以做读完数据的业务，writer可以做要发送消息之前的事情，实际也是为了以后做一些扩展性功能留的坑。

目前这个读写分离模型，也是为了配合worker工作池来分离的，reader每次将消息发送给worker工作池，wirter从worker工作池的任务对了取消息再执行业务的。 不知道我回答的是不是您要问的问题☺

**Comment by hellodudu** [comment]
嗯嗯，感谢，您能举个稍微具体点的例子来解释一下Connection的SendMsg和SendBuffMsg的适用场景吗？还有之前我说的费的问题不存在，是我看差了，channel传的是byte slice，效率没有问题。
