### ISSUE TITLE
ClearOneConn会有死锁吧

### ISSUE THREAD

**Issue by liutianpeng** [aceld/zinx#100]
func (connMgr *ConnManager) ClearOneConn中显示对ConnManager.connLock加锁,然后在函数结束才会解锁
conn.Stop()中会掉用ConnManager.Remove方法
ConnManager.Remove也会对ConnManager.connLock加锁
这里是会死锁的吧?

**Comment by liutianpeng** [comment]
func (connMgr *ConnManager) ClearConn()  应该也是吧?

**Comment by aceld** [comment]
是的，这个确实有个这个问题，稍后我们改进一下哈~感谢提供建议。

**Comment by aceld** [comment]
是的，这个确实有个这个问题，稍后我们改进一下哈~感谢提供建议。

**Comment by liutianpeng** [comment]
其实你都有context了 利用context管理连接不好吗？

**Comment by aceld** [comment]
Tag:v1.0.1 应该是解决了
