### ISSUE TITLE
用docker 打包测试例子的server，报 /zinx-server 不存在

### ISSUE THREAD

**Issue by LionSummer** [aceld/zinx#106]
dockerfile文件没动过
![image](https://user-images.githubusercontent.com/38936611/116535858-d605a180-a916-11eb-9e88-bde8817e967d.png)

**Comment by kstwoak** [comment]
你好，这个是因为你没有先将代码编译成为可执行文件，建议先执行make build 然后在执行make image。最后可以执行make run把容器进行运行。
