### ISSUE TITLE
对于文档的建议

### ISSUE THREAD

**Issue by hash-rabbit** [aceld/zinx#107]
网上关于go的tcp框架并不是很多,我觉得zinx还是不错的,但是文档确实感觉不是很适合新手.
作为一个第一次使用zinx框架的开发者来着,几乎翻遍了zinx的官方文档,但很可惜的是,几乎所有的文档都是在讲zinx怎么开发,而怎么使用少之又少,因为在首页readme和demo中我发现了很多问题,需要修改才可以使用,我觉得作者可以在**如何安装**、**如何使用**、包括**心跳路由**等如何使用,讲的详细一些,讲如何自己开发讲的少一些,效果会更好

**Comment by jumoshen** [comment]
+1，作者的文档讲的是框架如何实现，缺少使用文档

**Comment by aceld** [comment]
https://www.yuque.com/aceld/tsgooa/sbvzgczh3hqz8q3l   
文档链接在这里，文档也在逐步完善中。
