### ISSUE TITLE
提个测试到的问题

### ISSUE THREAD

**Issue by jiangjiali** [aceld/zinx#108]
如果用浏览器访问，程序立刻挂掉。
不知道作者有什么解决方案呢。

**Comment by VWmin** [comment]
浏览器访问用的Http协议，server用的是自定义协议。协议不一致，拆包出错可能就挂掉了。

**Comment by jiangjiali** [comment]
> 浏览器访问用的Http协议，server用的是自定义协议。协议不一致，拆包出错可能就挂掉了。

对。就是这个错误。

**Comment by jiangjiali** [comment]
> 浏览器访问用的Http协议，server用的是自定义协议。协议不一致，拆包出错可能就挂掉了。

我在拆包时看看怎么处理一下吧。

**Comment by xxl6097** [comment]
二楼的说的对
