### ISSUE TITLE
这个代码为什么又重新关闭一次

### ISSUE THREAD

**Issue by nnntlh** [aceld/zinx#112]
https://github.com/aceld/zinx/blob/0048291d51542cd5c747e09ba82573157dfef255/znet/connection.go#L165
https://github.com/aceld/zinx/blob/0048291d51542cd5c747e09ba82573157dfef255/znet/connection.go#L175
刚学习,请帮忙看一下,不太懂

**Comment by aceld** [comment]
修复了~感谢
