### ISSUE TITLE
并发情况下map会有死锁问题

### ISSUE THREAD

**Issue by georgezhangjiacheng** [aceld/zinx#114]
高并发情况下map会有死锁问题，在c.stop的时候，有时候会崩掉，具体情况不大清楚，不知道有没有人遇到过

**Comment by aceld** [comment]
@georgezhangjiacheng   bug已经修复，感谢 @huguijian ！

**Comment by obe007** [comment]
> @georgezhangjiacheng bug已经修复，感谢 @huguijian ！

请问下 atomic.Value 原子锁高并发情况下，不如 sync.RWMutex  读写锁吗？

**Comment by jiangjiali** [comment]
> > @georgezhangjiacheng bug已经修复，感谢 @huguijian ！
> 
> 请问下 atomic.Value 原子锁高并发情况下，不如 sync.RWMutex 读写锁吗？

我也有同样问题。

**Comment by jiangjiali** [comment]
> > @georgezhangjiacheng bug已经修复，感谢 @huguijian ！
> 
> 请问下 atomic.Value 原子锁高并发情况下，不如 sync.RWMutex 读写锁吗？

原子操作由底层硬件支持，而锁则由操作系统的调度器实现。锁应当用来保护一段逻辑，对于一个变量更新的保护，原子操作通常会更有效率。

**Comment by gufeijun** [comment]
atomic.Value的Load和Store只能保证存和取这两步时原子，它们无法保证(*ConnManeger)的Remove以及Get方法中对map的操作原子，因为此时map以及取出来。
