### ISSUE TITLE
CallOnConnStop 函数里面调用 sendMsg 会死锁

### ISSUE THREAD

**Issue by chnzrb** [aceld/zinx#117]
func (c *Connection) Stop() {
	**_c.Lock(_)**
	defer c.Unlock()
	fmt.Println("stop:", c.isClosed)
	//如果用户注册了该链接的关闭回调业务，那么在此刻应该显示调用
	**_c.TCPServer.CallOnConnStop(c)_**
        ......
}

func (c *Connection) SendMsg(msgID uint32, data []byte) error {
	**_c.RLock()_**
	defer c.RUnlock()
	if c.isClosed == true {
		return errors.New("connection closed when send msg")
	}
      ......
}
这两个地方加锁会出现死锁，导致connection 不能释放

**Comment by gufeijun** [comment]
OnConnStop回调函数调用的时机是连接出错或者用户主动调用Conn.Stop，这时连接已经关闭，不应该在这个回调函数里调用SendMsg方法，我觉得这是开发者自己的失误
