### ISSUE TITLE
两个小问题

### ISSUE THREAD

**Issue by heyangfan** [aceld/zinx#121]
在ConnManager内的ClearOneConn以及ClearConn方法 调用conn.Stop()方法后紧接着执行了delete(connMgr.connections, connID)方法。
但是可以看到的是在connection的Stop() 方法内调用了c.TCPServer.GetConnMgr().Remove(c) 而在ConnManager的Remove方法内已经删除过一次map元素了。

另外有一个疑惑的地方，对于connection的MsgHandler属性是通过Server传过来的，但是我看到了在connection里面是有IServer这个属性的，是否可以给server开放一个GetMsgHandler方法，然后去掉connection的MsgHandler 这个属性？例子：在connection内调用handler改为self.TCPServer.GetMsgHandler()。

如果是问题的话，建议优化，需要帮助的话，我也提PR，感谢刘大大提供的教学资料，受益匪浅~ ：）

**Comment by YanHeDoki** [comment]
第一点我也很疑惑，测试去掉delete方法依旧回去删除连接在map里
第二个map类型是引用类型传过去是指针复制一遍问题不大

**Comment by JiBadBoy** [comment]
> 第一点我也很疑惑，测试去掉delete方法依旧回去删除连接在map里 第二个map类型是引用类型传过去是指针复制一遍问题不大

已处理
