### ISSUE TITLE
有自己的配置文件和对应的读取方法，不想用默认的json配置

### ISSUE THREAD

**Issue by kerojiang** [aceld/zinx#123]
我有自己的一套配置文件和对应读取方法，我去创建Server的时候msgHandler参数小写开头，外层一直报错，这个小写是为啥呢？ 我不想用默认的json配置

**Comment by aceld** [comment]
配置文件的加载方式，您可以用自己的，在global.go里 将zinx的config reload的部分替换成自己的就可以了。
