### ISSUE TITLE
客户端链接直接发送字节流，不通过DataPack的的pack压缩的字节流，服务端无法收到

### ISSUE THREAD

**Issue by 601630051** [aceld/zinx#143]
在客户端链接服务端成功后，直接conn.Write([]byte("test"))，
在服务端func (c *Connection) StartReader() {}
无法接收到网络包信息
如果是通过
dp := znet.NewDataPack()
msg, err := dp.Pack(znet.NewMsgPackage(0, []byte("test")))
, err = conn.Write(msg)

在服务端端就能收到

**Comment by zhangruishipangpang** [comment]
这里的问题是在unpack过程中会先读取数据长度，因为你没按照规则pack你的数据包，所以程序中会取“test”的ASCII码进行运算。导致程序打印错误信息。可以debug下面两点，看下取的值就了解了。

![image](https://user-images.githubusercontent.com/54319255/178682696-26b045f5-d479-457d-b82f-dc68ff7af4ad.png)

**Comment by JiBadBoy** [comment]
> 

可以了解一下TLV
