### ISSUE TITLE
关于Conn的SendBuffMsg

### ISSUE THREAD

**Issue by AlespRless** [aceld/zinx#150]
这里采用了带缓存的channel向write协程发送数据,但是这是不是没有什么必要?
对于服务器来说发送的速度取决于服务器这边,就算采用了带缓存的channel实际上也只是增加了一点发送数据的延迟而已,因为write协程在不断从channel中获取数据并发送给客户端.
求刘老师指导 ; w ;

**Comment by hessonsu** [comment]
确实。我看到这里也是懵逼。直接向SendMsg 一样直接写到链接里面。有什么问题呢？

**Comment by stbzyjy** [comment]
应该是为了避免发送数据操作阻塞消息处理逻辑吧。SendMsg中使用了RLock会加重系统开销，使用协程应该也有避免加锁的考量。

**Comment by Woodswu** [comment]
你看代码里面，有没有这么一种情况，客户端响应慢了，会不会把你服务器拖死

**Comment by xxl6097** [comment]
作为服务端，使用消息队列是十分有必要的。你说的情况，就几十几百的连接量可以不使用线程池和消息队列。如果遇到上万连接同时并发发送数据，问题就严重了哈
