### ISSUE TITLE
客户端断电或者拔出网线，服务端有时等了很久也不会触发doConnectionLost事件

### ISSUE THREAD

**Issue by twxstar** [aceld/zinx#155]
目前的版本客户端和服务端的超时判断需要自行处理，还是有一定的机制在判断

**Comment by maxbad** [comment]
客户端连接上后,什么都不操作,也不会断开, 需要自己写代码断开客户端吗?

**Comment by twxstar** [comment]
> 客户端连接上后,什么都不操作,也不会断开, 需要自己写代码断开客户端吗?

客户端拔掉网线，服务端不会触发doConnectionLost事件

**Comment by twxstar** [comment]
客户端和服务端定期发送心跳包，服务端判断一段时间内没有客户端的心跳包，就断开客户端的连接

**Comment by Woodswu** [comment]
这个开发者 给提供了一个 ztimer 时间轮子的东西，你可以使用，在包里面就有，可以 在建立连接的时候doconnection的时候 执行，在60秒后调用，可以close掉连接

**Comment by aceld** [comment]
https://github.com/aceld/zinx/tree/master/examples/zinx_heartbeat zinx提供了心跳机制，可以使用
