### ISSUE TITLE
ConnManager.ClearConn 调用了stop还去delete ConnManager的map中的链接是否是多此一举

### ISSUE THREAD

**Issue by YanHeDoki** [aceld/zinx#161]
```
//ClearConn 清除并停止所有连接
func (connMgr *ConnManager) ClearConn() {
	connMgr.connLock.Lock()
       //停止并删除全部的连接信息
	for connID, conn := range connMgr.connections {
		//停止
		conn.Stop()
		//删除
		delete(connMgr.connections, connID)
	}
	connMgr.connLock.Unlock()
	fmt.Println("Clear All Connections successfully: conn num = ", connMgr.Len())
}
```
其中调用了conn.Stop()
而conn.Stop()触发后会 finalizer() 其中会调用

```
//将链接从连接管理器中删除
	c.TCPServer.GetConnMgr().Remove(c)
```
这会把连接从map中删除，还主动del map里的链接是否多此一举

**Comment by YanHeDoki** [comment]
我测试一下注释delete(connMgr.connections, connID)
之后模拟1000个连接测试一下，是依旧会清空的

	
	type PingRouter struct {
		znet.BaseRouter
	}
	
	// test handleRouter
	func (p *PingRouter) Handle(req ziface.IRequest) {
	
	if err := req.GetConnection().SendMsg(0, []byte("ping...ping...ping")); err != nil {
		fmt.Println(err)
		}
	
	}
	
	
	func main() {
		fmt.Println("test Zinx-V0.10")
		server := znet.NewServer()
		server.AddRouter(0, &PingRouter{})
		
	go func() {
		time.AfterFunc(5*time.Second, func() {
			fmt.Println(server.GetConnMgr().Len())
			server.GetConnMgr().ClearConn()
			time.Sleep(time.Millisecond)
			fmt.Println(server.GetConnMgr().Len())
		})
	}()
	
	server.Server()
	}


//模拟客户端

	func main() {
	for i:=0;i<1000;i++{
		go func() {
			//1创建直接链接
			conn, err := net.Dial("tcp", "127.0.0.1:8999")
			if err != nil {
				fmt.Println("net dial err:", err)
				return
			}
			defer conn.Close()
			//链接调用write方法写入数据
			for {
				dp := znet.NewDP()
				msg, err := dp.Pack(znet.NewMsgPackage(0, []byte("test ")))
				if err != nil {
					return
				}
				_, err = conn.Write(msg)
	
				if err != nil {
					return
				}
				headdata := make([]byte, dp.GetHeadLen())
				_, err = io.ReadFull(conn, headdata)
				if err != nil {
					fmt.Println("read head error")
					break
				}
				msghead, err := dp.UnPack(headdata)
				if err != nil {
					fmt.Println("server unpack err:", err)
					return
				}
				if msghead.GetDataLen() > 0 {
					//msg 是有data数据的，需要再次读取data数据
					msg := msghead.(*znet.Message)
					msg.Data = make([]byte, msg.GetDataLen())
					_, err := io.ReadFull(conn, msg.Data)
					if err != nil {
						fmt.Println("server unpack data err:", err)
						return
					}
					fmt.Println("==> Recv Msg: ID=", msg.Id, ", len=", msg.DataLen, ", data=", string(msg.Data))
				}
				time.Sleep(1 * time.Second)
			}
		}()
	}
	select {}
	}

**Comment by YanHeDoki** [comment]
`fmt.Println(server.GetConnMgr().Len())`   最后的这里打印是0

**Comment by JiBadBoy** [comment]
> 我测试一下注释delete(connMgr.connections, connID) 之后模拟1000个连接测试一下，是依旧会清空的
> 
> ```
> type PingRouter struct {
> 	znet.BaseRouter
> }
> 
> // test handleRouter
> func (p *PingRouter) Handle(req ziface.IRequest) {
> 
> if err := req.GetConnection().SendMsg(0, []byte("ping...ping...ping")); err != nil {
> 	fmt.Println(err)
> 	}
> 
> }
> 
> 
> func main() {
> 	fmt.Println("test Zinx-V0.10")
> 	server := znet.NewServer()
> 	server.AddRouter(0, &PingRouter{})
> 	
> go func() {
> 	time.AfterFunc(5*time.Second, func() {
> 		fmt.Println(server.GetConnMgr().Len())
> 		server.GetConnMgr().ClearConn()
> 		time.Sleep(time.Millisecond)
> 		fmt.Println(server.GetConnMgr().Len())
> 	})
> }()
> 
> server.Server()
> }
> ```
> 
> //模拟客户端
> 
> ```
> func main() {
> for i:=0;i<1000;i++{
> 	go func() {
> 		//1创建直接链接
> 		conn, err := net.Dial("tcp", "127.0.0.1:8999")
> 		if err != nil {
> 			fmt.Println("net dial err:", err)
> 			return
> 		}
> 		defer conn.Close()
> 		//链接调用write方法写入数据
> 		for {
> 			dp := znet.NewDP()
> 			msg, err := dp.Pack(znet.NewMsgPackage(0, []byte("test ")))
> 			if err != nil {
> 				return
> 			}
> 			_, err = conn.Write(msg)
> 
> 			if err != nil {
> 				return
> 			}
> 			headdata := make([]byte, dp.GetHeadLen())
> 			_, err = io.ReadFull(conn, headdata)
> 			if err != nil {
> 				fmt.Println("read head error")
> 				break
> 			}
> 			msghead, err := dp.UnPack(headdata)
> 			if err != nil {
> 				fmt.Println("server unpack err:", err)
> 				return
> 			}
> 			if msghead.GetDataLen() > 0 {
> 				//msg 是有data数据的，需要再次读取data数据
> 				msg := msghead.(*znet.Message)
> 				msg.Data = make([]byte, msg.GetDataLen())
> 				_, err := io.ReadFull(conn, msg.Data)
> 				if err != nil {
> 					fmt.Println("server unpack data err:", err)
> 					return
> 				}
> 				fmt.Println("==> Recv Msg: ID=", msg.Id, ", len=", msg.DataLen, ", data=", string(msg.Data))
> 			}
> 			time.Sleep(1 * time.Second)
> 		}
> 	}()
> }
> select {}
> }
> ```

是的，可以去掉，我处理一下

**Comment by JiBadBoy** [comment]
> delete(connMgr.connections, connID)

是的，可以去掉，我处理一下
