### ISSUE TITLE
Zinx添加一个ID和连接的映射

### ISSUE THREAD

**Issue by YanHeDoki** [aceld/zinx#169]
提议 Zinx中可以添加一个Notify 层用来绑定用户传入的id和当前的连接映射 以提供以下功能呢
1.检验当前id是否已有链接
2.提供通过id通知某一用户的的方法接口
3.可以一次性对所有玩家通知消息

**Comment by aceld** [comment]
已经merge，非常的棒👍🏻

**Comment by YanHeDoki** [comment]
> 已经merge，非常的棒👍🏻
好的
