### ISSUE TITLE
connection  StartReader  处理数据,解码之后只有数据前8位,导致数据丢失

### ISSUE THREAD

**Issue by clukboy** [aceld/zinx#178]
![image](https://user-images.githubusercontent.com/89188315/226269156-839341db-ad8b-4de6-aeeb-64405d3590a4.png)

zinx：1.1.2版本,1.1.0 无任何问题

**Comment by xxl6097** [comment]
你的协议是什么样的？如果没有设置解码器，默认是TLV格式协议

**Comment by xxl6097** [comment]
最好附上你的测试数据

**Comment by xxl6097** [comment]
> ![image](https://user-images.githubusercontent.com/89188315/226269156-839341db-ad8b-4de6-aeeb-64405d3590a4.png)
> 
> zinx：1.1.2版本,1.1.0 无任何问题

你的协议是什么样的？如果没有设置解码器，默认是TLV格式协议.最好附上你的测试数据

**Comment by clukboy** [comment]
> > ![image](https://user-images.githubusercontent.com/89188315/226269156-839341db-ad8b-4de6-aeeb-64405d3590a4.png)
> > zinx：1.1.2版本,1.1.0 无任何问题
> 
> 你的协议是什么样的？如果没有设置解码器，默认是TLV格式协议.最好附上你的测试数据

我使用的是默认的配置，任务东西都没有碰。下面是我的测试数据
![image](https://user-images.githubusercontent.com/89188315/226280952-dbbb2d7f-4dc6-4027-b164-77683b4545cd.png)

**Comment by xxl6097** [comment]
我解释一下，这里存在两个问题：
1、client.GetPacket().Pack，这里的Pack使用的是小端模式，但是服务器默认是大端；
2、这里的Pack封装的是LTV模式，但是服务器默认是是TLV，请一定注意写msgID和dataLen的前后顺序

代码如下：
```

func Pack(msg ziface.IMessage) ([]byte, error) {
	dataBuff := bytes.NewBuffer([]byte{})
	//写msgID
	if err := binary.Write(dataBuff, binary.BigEndian, msg.GetMsgID()); err != nil {
		return nil, err
	}

	//写dataLen
	if err := binary.Write(dataBuff, binary.BigEndian, msg.GetDataLen()); err != nil {
		return nil, err
	}

	//写data数据
	if err := binary.Write(dataBuff, binary.BigEndian, msg.GetData()); err != nil {
		return nil, err
	}

	return dataBuff.Bytes(), nil
}

func main() {
	client := znet.NewClient("127.0.0.1", 8999)
	client.SetOnConnStart(func(conn ziface.IConnection) {
		//msg, _ := client.GetPacket().Pack(zpack.NewMsgPackage(0, []byte("hello")))
		msg, _ := Pack(zpack.NewMsgPackage(0, []byte("hello")))
		//请注意，msg数据在zpack中使用的小端模式，但是服务器默认是大端哦
		zlog.Ins().DebugF("send msg %s \n", hex.EncodeToString(msg))
		_, err := conn.GetConnection().Write(msg)
		fmt.Println(err)
	})

	client.Start()
	select {}
}
```

**Comment by xxl6097** [comment]
请阅读aceld/zinx@v1.1.2/examples/LTVDecoder.go文件，专门针对LTV协议格式做出的解释与处理

**Comment by clukboy** [comment]
PackData 下面的Pack 是否需要更新一下呢，他这里还是使用的先DataLen 在msgID的
![image](https://user-images.githubusercontent.com/89188315/226308603-378d6d5f-f264-4fbf-b63f-19f2f2f51e05.png)

**Comment by clukboy** [comment]
我使用protobuf来传输数据的时候,他解析出来也是存在问题的。proto unmarshal err:proto: cannot parse invalid wire-format data,我通过断点查看,MsgData其实并没有把MsgId和DataLen去除,还是在包里面的，这样的话就等于还需要自己重新解析一次
![image](https://user-images.githubusercontent.com/89188315/226311938-f5b5897e-e464-4cba-8756-12f92b246fc5.png)

**Comment by clukboy** [comment]
我看了，使用这个解码采用的response来读取数据没问题，但是如果不采用的话还需要自己重新拆包一下，

**Comment by aceld** [comment]
@clukboy 确实，，我们应该先兼容一下之前的，这个原因是近期我们新增了一套解码器，可以提供自定义报文格式的，可能在之前暴露出来的接口没有兼容好，你可以先用下v1.1.0， 这几天我们会兼容下之前的接口，之后会打个tag，在这里回复。

**Comment by xxl6097** [comment]
使用v1.1.3版本，解决以上问题

**Comment by clukboy** [comment]
> 使用v1.1.3版本，解决以上问题

![image](https://user-images.githubusercontent.com/89188315/226530238-f315d061-c5d6-420c-8b05-328da5e12a61.png)
 
还是不行，数据还是没有解析，应该默认是不初始化解码器才是正确的，由用户来初始化解码器就行了

**Comment by xxl6097** [comment]
> > 使用v1.1.3版本，解决以上问题
> 
> ![image](https://user-images.githubusercontent.com/89188315/226530238-f315d061-c5d6-420c-8b05-328da5e12a61.png)
> 
> 还是不行，数据还是没有解析，应该默认是不初始化解码器才是正确的，由用户来初始化解码器就行了

你这个地方说的没错，但是为了兼容以前版本，所以才设置默认。如果你不想要默认的，可以自行设置s.SetDecoder(nil)
使用v1.1.5版本目前存在的问题应该都已经解决！
