### ISSUE TITLE
冰哥，最新更新消息丢给责任链这个源码，看不懂，能不能开个教程啊！

### ISSUE THREAD

**Issue by Xuzan9396** [aceld/zinx#185]
<img width="230" alt="image" src="https://user-images.githubusercontent.com/24741439/227762141-561e67cd-8e6a-4478-a01e-290fe1980d7f.png">

**Comment by fivezjd** [comment]
冰哥的拦截器设计类似web框架的中间件，拦截器有两个关键点：

1. 拦截管理器  RealInterceptorChain 
2. 拦截器  interceptor

拦截管理器  RealInterceptorChain 主要作用是维护一个切片interceptors,用来管理所有要执行的拦截器，`func (this *RealInterceptorChain) Proceed(request ziface.Request) ziface.Response` 这个是拦截管理器的一个方法，用来执行拦截管理器中的拦截器，你可以看到，他的入参是一个 `ziface.Request`，而` ziface.Request` 是一个空接口，在每个拦截器interceptor执行Intercept() 的时候，会递归的调用Proceed(),这样会依次执行完拦截管理器中的所有拦截器，类似web框架中的next()

**拦截管理器执行**

`func (this *RealInterceptorChain) Proceed(request ziface.Request) ziface.Response {
	if this.position < len(this.interceptors) {
		chain := NewRealInterceptorChain(this.interceptors, this.position+1, request)
		interceptor := this.interceptors[this.position]
		response := interceptor.Intercept(chain) // 执行拦截器的拦截方法
		return response
	}
	return request
}`

**递归调用**
`
// 拦截器的拦截方法
func (this *MsgHandle) Intercept(chain ziface.Chain) ziface.Response {
	request := chain.Request()
	if request != nil {
		switch request.(type) {
		case ziface.IRequest:
			iRequest := request.(ziface.IRequest)
			if utils.GlobalObject.WorkerPoolSize > 0 {
				//已经启动工作池机制，将消息交给Worker处理
				this.SendMsgToTaskQueue(iRequest)
			} else {
				//从绑定好的消息和对应的处理方法中执行对应的Handle方法
				go this.DoMsgHandler(iRequest)
			}
		}
	}
	// 递归调用拦截器的执行方法，进行下一个拦截器的执行
	return chain.Proceed(chain.Request())
}`

**Comment by Xuzan9396** [comment]
明白了，谢谢，设计模式值得学习

**Comment by xxl6097** [comment]
这个是仿的 okhttp 里面的责任链设计模式，想了解全部，可以去查看 okhttp 的拦截器

**Comment by aceld** [comment]
https://www.yuque.com/aceld/tsgooa/zn0y6xpynrzfd1z5 
这部分zinx文档里有有说明。
