### ISSUE TITLE
连接id，只能固定系统自动生成吗？

### ISSUE THREAD

**Issue by lala0257** [aceld/zinx#188]
业务需求如下， 每个设备(账号)唯一， 能不能把连接id抽出来（这里不用系统固定自动生成），可以由用户指定生成连接。或者有没有其它思路
> //3.3 处理该新连接请求的 业务 方法， 此时应该有 handler 和 conn是绑定的
dealConn := newServerConn(s, conn, cID)
cID++

**Comment by lala0257** [comment]
···

**Comment by xxl6097** [comment]
> 个设

如题你所说，你也提到了是业务需求。框架是不能处理这样的业务需求的。连接ID你是可以获取并维护的

**Comment by xxl6097** [comment]
> 业务需求如下， 每个设备(账号)唯一， 能不能把连接id抽出来（这里不用系统固定自动生成），可以由用户指定生成连接。或者有没有其它思路
> 
> > //3.3 处理该新连接请求的 业务 方法， 此时应该有 handler 和 conn是绑定的
> > dealConn := newServerConn(s, conn, cID)
> > cID++

如题你所说，你也提到了是业务需求。框架是不能处理这样的业务需求的。连接ID你是可以获取并维护的
