### ISSUE TITLE
[Bug]: 程序卡死

### ISSUE THREAD

**Issue by GStones** [aceld/zinx#189]
https://github.com/aceld/zinx/blob/46a2e95a3f3c5998e930792f81207a37ef43cec4/znet/connection.go#L128

这块代码如果报错，会导致`msgBuffChan` 没有协程消费，进而导致`worker pool` 消耗光，程序直接卡死

**Comment by xxl6097** [comment]
> https://github.com/aceld/zinx/blob/46a2e95a3f3c5998e930792f81207a37ef43cec4/znet/connection.go#L128
> 
> 这块代码如果报错，会导致`msgBuffChan` 没有协程消费，进而导致`worker pool` 消耗光，程序直接卡死

可以把错误信息贴出来吗？这个地方能报什么错误，就算报错了，也retrun了

**Comment by GStones** [comment]
我这边遇到的是`broken pipe` 的报错

**Comment by aceld** [comment]
@GStones 可能会出现这个问题，这个return改成break应该就可以了

**Comment by aceld** [comment]
@GStones  https://github.com/aceld/zinx/commit/97f26521ff8821314816fc8511a56ae0779cc2ed
