### ISSUE TITLE
生产环境下的log

### ISSUE THREAD

**Issue by LI-GUOJIE** [aceld/zinx#199]
请问目前有进一步完善log的计划吗。或者，我可以对zinx-log进行修改并提交吗？

生产环境下：
1，需要屏蔽info级别的日志（通过zinx.json控制）
2，将error和fatal信息通过webhook（比如飞书/Wechat的消息机器人）通知管理员
3，log文件名带上日期前缀（或后缀），比如2023-0407-0.log
4，log文件尺寸超过一定程度（比如50MB）时，打印到新文件中，比如2023-0407-1.log

**Comment by hcraM41** [comment]
1.隔离级别：一般生产环境隔离的是debug，很少会隔离info，但是也可以补充下这个点；
2.第三方notify接入：这个个人感觉没太大必要接入到框架中，毕竟是轻量级的，项目自己需要自己接就好了，而且每个人不一定适用；
3.文件后缀带日期的已经补充
4.这个除非出了故障，不然生产环境中一天的日志量应该不会太大，可以考虑补充这个点；
