### ISSUE TITLE
2个问题

### ISSUE THREAD

**Issue by wukongyong** [aceld/zinx#215]
1.zinx/zinterceptor/framedocder.go文件559行，如果InitialBytesToStrip不为零，会有脏数据被剩余下来

**Comment by wukongyong** [comment]
2.zinx/net/client.go文件110行，客户端重连，每次都会加入一个新的拦截器

**Comment by aceld** [comment]
@wukongyong  问题2， 是否可以考虑再提供一个restart()方法给Client。
问题1，需要 @xxl6097 帮忙回答下了。
