### ISSUE TITLE
ShardLockMaps的GetShard方法内应该使用结构体中的shareKeyFunc而非fnv32

### ISSUE THREAD

**Issue by cyj19** [aceld/zinx#268]
感谢作者写出这个宝藏项目，我的问题如下：
```
// GetShard returns shard under given key
func (slm ShardLockMaps) GetShard(key string) *SingleShardMap {
	return slm.shards[fnv32(key)%uint32(ShardCount)]
}
```
因为提供了创建函数`NewWithCustomShardKeyFunc` ，上述代码应该改为：
```
func (slm ShardLockMaps) GetShard(key string) *SingleShardMap {
	return slm.shards[slm.shardKeyFunc(key)%uint32(ShardCount)]
}
```
否则创建函数`NewWithCustomShardKeyFunc` 失去了意义，哈希函数只能`fnv32`。

**Comment by aceld** [comment]
@hcraM41  look look.

**Comment by hcraM41** [comment]
> 感谢作者写出这个宝藏项目，我的问题如下：
> 
> ```
> // GetShard returns shard under given key
> func (slm ShardLockMaps) GetShard(key string) *SingleShardMap {
> 	return slm.shards[fnv32(key)%uint32(ShardCount)]
> }
> ```
> 
> 因为提供了创建函数`NewWithCustomShardKeyFunc` ，上述代码应该改为：
> 
> ```
> func (slm ShardLockMaps) GetShard(key string) *SingleShardMap {
> 	return slm.shards[slm.shardKeyFunc(key)%uint32(ShardCount)]
> }
> ```
> 
> 否则创建函数`NewWithCustomShardKeyFunc` 失去了意义，哈希函数只能`fnv32`。

good issues~自定义创建函数是后续提供的，GetShard 漏改了，欢迎pr~
