### ISSUE TITLE
How to send mesaage from server to cleint?

### ISSUE THREAD

**Issue by thinkgos** [aceld/zinx#298]
How to send mesaage from server to cleint? I want to server actively send messages to client. not just C -> S mode.

**Comment by aceld** [comment]
@thinkgos 
You can refer to the code at https://github.com/aceld/zinx/blob/master/zinx_app_demo/mmo_game/core/player.go#L368

```go
func (p *Player) LostConnection() {
	// 1 Get players in the surrounding AOI nine-grid
	// 获取周围AOI九宫格内的玩家
	players := p.GetSurroundingPlayers()

	// 2 Assemble MsgID:201 message
	// 封装MsgID:201消息
	msg := &pb.SyncPID{
		PID: p.PID,
	}

	// 3 Send messages to surrounding players
	// 向周围玩家发送消息
	for _, player := range players {
		player.SendMsg(201, msg)
	}

	// 4 Remove the current player from AOI in the world manager
	// 世界管理器将当前玩家从AOI中摘除
	WorldMgrObj.AoiMgr.RemoveFromGrIDByPos(int(p.PID), p.X, p.Z)
	WorldMgrObj.RemovePlayerByPID(p.PID)
```

This method handles a client disconnection, and the server actively broadcasts a message to other clients. This is an online game example using Zinx, and I hope it helps.

**Comment by thinkgos** [comment]
@aceld thanks
