### ISSUE TITLE
[Warnning]: Request 对象池机制问题

### ISSUE THREAD

**Issue by GStones** [aceld/zinx#308]
当前Request 对象池机制会导致传递到其他线程的Request内容改变，虽然提供了COPY方法，但是会严重影响之前版本的实现，并且不好定位问题，提个Issues提醒下各位，升级需谨慎

**Comment by aceld** [comment]
@GStones 收到这个问题，有没有一些具体的场景，和你目前业务做的兼容写法的改动。 我们这边也尽量想一个可以兼容之前版本的实现。

**Comment by YanHeDoki** [comment]
@GStones #312 现在添加了开关，只有在手动开启池化模式后才会采用对象池模式，默认和之前的行为保持一致。
