### ISSUE TITLE
如果我用其他语言写一个客户端，怎么才能触发路由

### ISSUE THREAD

**Issue by WyntersN** [aceld/zinx#309]
s.AddRouter(10000, &api.Client{})

如果我用其他语言写一个客户端，怎么才能触发10000路由，什么用什么格式发送的啊，我自己用其他语言连接没问题 客户端发送消息服务器一直收不到，也不知道 msgid 在其他客户端上怎么实现

**Comment by clukboy** [comment]
可能你发送的数据包无法解析，
1. 第一种解决办法，你可以重写decoder 来完成你的数据解析.通过你数据包的tag来指向到对应的路由
2. 第二种解决办法，可以在你客户端程序封包的时候按照你服务端的解码来进行封包也可以解决你的问题。

**Comment by valiner** [comment]
前后端 统一 编解码 即可
我用webscoket的，我直接自己写个json的编码器

**Comment by valiner** [comment]
> Re

https://www.yuque.com/aceld/tsgooa/lsu25bgvqoxeg6nz
