### ISSUE TITLE
socket tcp 在连接的时候怎么做鉴权，例如根据 token 做连接认证

### ISSUE THREAD

**Issue by JeffreyBool** [aceld/zinx#31]

**Comment by aceld** [comment]
目前没有加token,有时间你可以加一下，如果加的话，流程可以参考如下：
1、首先通过普通的connect请求服务器建立连接, tcp 三次握手要完成，服务器首先返回token
2、客户端拿token去请求接口，服务器校验token，校验通过，确认链接建立成功，加入到Manager中，如果token失败，则close。

**Comment by xdlgj** [comment]
这样的话任何一个客户端都可以获取到token，是不是相当于没有鉴权。
可不可以这样做：
1、服务器设置token，通过人为的方式把这个token写在客户端。
2、客户端连接成功后主动发送一次token，如果验证成功，就给这个连接设置一个属性表示已经鉴权，可以做后面的数据传输。
3、如果在发送其他数据的时候，连接没有这个属性，服务器就主动断开该次连接。
