### ISSUE TITLE
go GC会不会影响性能？

### ISSUE THREAD

**Issue by tylitianrui** [aceld/zinx#32]
游戏框架性能是有所要求的。go的 GC一直被诟病，是否可以采用sync.Pool进行优化

**Comment by kstwoak** [comment]
go的Gc其实到目前的效率性对程序的性能影响已经很小了

**Comment by tylitianrui** [comment]
@kstwoak 有具体的性能对比吗？

**Comment by kstwoak** [comment]
@tylitianrui  1.5   300ms(毫秒)左右不超过400ms(毫秒)

1.6   40左右ms(毫秒)

1.62 是10-20ms(毫秒)左右

1.63 5ms(毫秒)以下

1.7   2ms(毫秒)以下

1.80 1ms(毫秒)左右差不多就1以下了 ms(毫秒)
