### ISSUE TITLE
拦截器中获取msgid，一直为0

### ISSUE THREAD

**Issue by LogicHou** [aceld/zinx#324]
您好，请问下我在拦截器中获取msgid一直为0，是怎么回事呢，代码如下

```
package main

import (
	"fmt"
	"github.com/aceld/zinx/ziface"
	"github.com/aceld/zinx/znet"
)


type HelloRouter struct {
	znet.BaseRouter
}

func (hr *HelloRouter) Handle(request ziface.IRequest) {
	//zlog.Ins().InfoF(string(request.GetData()))
	fmt.Println(string(request.GetData()))
}

type MyInterceptor struct{}

func (m *MyInterceptor) Intercept(chain ziface.IChain) ziface.IcResp {
	request := chain.Request() //从责任链中获取当前拦截器的输入数据
    
	// 这一层是自定义拦截器处理逻辑，这里只是简单打印输入
	iRequest := request.(ziface.IRequest) //注意：由于Zinx的Request类型，这里需要做一下断言转换
    
	fmt.Printf("自定义拦截器, 收到消息：%s", iRequest.GetData())
        fmt.Printf("GetMsgID：%d", iRequest.GetMsgID()) //这里获取的msgid为0
    
	return chain.Proceed(chain.Request()) //进入并执行下一个拦截器
}

func main() {
	// 创建server 对象
	server := znet.NewServer()
	// 添加路由映射
	server.AddRouter(1, &HelloRouter{})
	// 添加自定义拦截器
	server.AddInterceptor(&MyInterceptor{})
	// 启动服务
	server.Serve()
}

```

**Comment by LogicHou** [comment]
另外再拦截器里获取消息体，前面好像会额外带上一个符号，比如发送`conn.SendMsg(1, []byte("Ping...Ping...Ping...[FromClient]"))`，拦截器里打印`fmt.Printf("自定义拦截器, 收到消息：%s", iRequest.GetData())`会打印出`自定义拦截器, 收到消息：!Ping...Ping...Ping...[FromClient]`

**Comment by GStones** [comment]
因为`Decoder` 是在`server.Serve()` 中添加到拦截器里面的，在 `server.AddInterceptor(&MyInterceptor{})` 之后，
所以执行顺序是：msg->MyInterceptor ->Decoder->handler ,从而导致`MyInterceptor` 获取不到解析的`msgID`

参考代码： https://github.com/aceld/zinx/blob/master/znet/server.go#L423-L425

**Comment by aceld** [comment]
> 因为`Decoder` 是在`server.Serve()` 中添加到拦截器里面的，在 `server.AddInterceptor(&MyInterceptor{})` 之后， 所以执行顺序是：msg->MyInterceptor ->Decoder->handler ,从而导致`MyInterceptor` 获取不到解析的`msgID`
> 
> 参考代码： https://github.com/aceld/zinx/blob/master/znet/server.go#L423-L425
> 
> * 这个PR将会优化这个问题  [fix(decoder): move decoder to interceptor head #325](https://github.com/aceld/zinx/pull/325)

666

**Comment by LogicHou** [comment]
收到，感谢各位解答
