### ISSUE TITLE
心跳panic

### ISSUE THREAD

**Issue by pingqiang806796422** [aceld/zinx#334]
![1](https://github.com/user-attachments/assets/5c1916df-1aa1-479d-adeb-51af5ac8765a)
![2](https://github.com/user-attachments/assets/3df3f1d9-5cff-4ad1-a5e6-ff01f464009b)
![3](https://github.com/user-attachments/assets/a5b9b0bb-e731-4bed-aa43-a18c23807bec)

**Comment by aceld** [comment]
@pingqiang806796422   
`Run()` 有一段注释，这个代码是注释掉了，还是应该有的？

**Comment by pingqiang806796422** [comment]
目前是因为有问题，才注释掉的

**Comment by aceld** [comment]
你 先拉下 master 分支，看能否还复现

**Comment by pingqiang806796422** [comment]
我们现在心跳不是双向的吗， 可以新增配置 单项吗？服务端不主动发送消息给客户端

**Comment by aceld** [comment]
@pingqiang806796422 目前还不支持单向，一旦开启就是双向，如果想只做单向处理，可以将 一方的OnRemoteNotAlive() 方法设置为不处理，忽略心跳消息。

**Comment by aceld** [comment]
@pingqiang806796422  `SetHeartbeatFunc()` 可以自定义一方的心跳检测，不发送心跳包。

**Comment by aceld** [comment]
```go
func (h *HeartbeatChecker) check() (err error) {

	if h.conn == nil {
		return nil
	}

	if !h.conn.IsAlive() {
		h.onRemoteNotAlive(h.conn)
	} else {
		if h.beatFunc != nil {
			err = h.beatFunc(h.conn)
		} else {
			err = h.SendHeartBeatMsg()
		}
	}

	return err
}
```

如果设置beatFunc 则每次心跳执行beatFunc，如果不设置才会给对方发送心跳报文

**Comment by pingqiang806796422** [comment]
目前我设置了beatFunc，  前面的问题，测试不出来了，因为不会发送心跳到客户端了
