### ISSUE TITLE
如果程序里同时启动了 Server 和 Client ，GlobalObject 混淆的问题

### ISSUE THREAD

**Issue by RoshanDev** [aceld/zinx#347]
Server 的 WorkerPoolSize 设为10，但是 client Restart 时就会将 zconf.GlobalObject.WorkerPoolSize 设置为 0，影响了 server 的 MsgHandle 的 Intercept 里，根据 zconf.GlobalObject.WorkerPoolSize 来判断是否大于 0 ，来启动工作池机制。

**Comment by aceld** [comment]
@RoshanDev 看了下，确实存在这个问题，我们看看怎么避免下。

**Comment by aceld** [comment]
@RoshanDev  https://github.com/aceld/zinx/pull/350 这个PR修复了这个问题，你再看看，是否还存在，拉master分支
