### ISSUE TITLE
关于获取head len 问题

### ISSUE THREAD

**Issue by fankys2012** [aceld/zinx#4]
`//获取包头长度方法
func(dp *DataPack) GetHeadLen() uint32 {
	//Id uint32(4字节) +  DataLen uint32(4字节)
	return 8
}`
uint32 在64位机器上是 64bits 8个字节了。

**Comment by aceld** [comment]
不会的，int或者uint 在不同平台操作系统数据占位大小会有有差异，比如int、uint在32位操作系统是4个字节(32位)、在64位操作系统中是8个字节(64位), 但是一旦数据类型定义为uint32或uint64，后面带有数字的数据类型，说明就已经与平台无关了，这么定义变量也是为了平台的移植考虑的，所以uint32无论跑在32位操作系统还是64位操作系统都是4个字节(32位)。

**Comment by fankys2012** [comment]
受教，感谢！
