### ISSUE TITLE
细节

### ISSUE THREAD

**Issue by JiBadBoy** [aceld/zinx#5]
1. globalobj.go 中init已经调用Reload了

![image](https://user-images.githubusercontent.com/15551658/56491662-df83f400-651b-11e9-8ce0-ece41be0b534.png)

2. 这个地方是不是直接用g参数
![image](https://user-images.githubusercontent.com/15551658/56491752-2a9e0700-651c-11e9-99ef-9a8cccc83cf5.png)

**Comment by aceld** [comment]
多谢，您提出的两点都非常正确，这边已经采纳， reload确实重复调用了， 对于传参，传入this指针确实更顺畅一些。 感谢哈~！代码已经更正了。

**Comment by JiBadBoy** [comment]
1. 内容调用 是不是直接可以用c.Conn 
![image](https://user-images.githubusercontent.com/15551658/56632491-9606e680-668c-11e9-954e-6e8c08a9dabb.png)

**Comment by aceld** [comment]
> 1. 内部调用 是不是直接可以用c.Conn
>    ![image](https://user-images.githubusercontent.com/15551658/56632491-9606e680-668c-11e9-954e-6e8c08a9dabb.png)

是的，直接取c.Conn更好一些，少了一层压栈，非常感谢。已经修正。

**Comment by JiBadBoy** [comment]
1. 这个直接是s
![image](https://user-images.githubusercontent.com/15551658/56722844-6d5d1a80-677a-11e9-939e-c93725f3ff73.png)
