### ISSUE TITLE
不应该合并#48的代码

### ISSUE THREAD

**Issue by zshorz** [aceld/zinx#51]
#48 中做的修改是完全不需要的
`go.mod` 文件只编译的时候有用，从git仓库拉取包并不是按照`go.mod`中的名字进行的
`go.mod`文件中` module github.com/aceld/zinx`这个名字使用`zinx`也是可以的
在zinx下面的包互相引用，不需要吧仓库地址也带上， `import "zinx/ziface"` 的引用方式是正确的

在新的项目中，如果用到`zinx`，包的导入应该这么写
```go
import (
	"github.com/aceld/zinx/znet"
        "github.com/aceld/zinx/ziface"
)
```
`zinx`不是包，只是一个文件夹，go的包都必须在目录里包含`.go`文件，且有`package 包名`

另外：不需要跟踪`go.sum`文件
建议按照`va.b.c`的格式发布一个release，否则在`go mod tidy`拉取的时候，都是按最后一次提交拉取，这会产生变化，`go.mod`文件为的就是保证版本一致，没有release的情况下版本总是`v0.0.0`

**Comment by zshorz** [comment]
#52

**Comment by zshorz** [comment]
不是go mod 模式会有问题

**Comment by zseeker** [comment]
@zshorz 既然该项目有go.mod，就应该按照规范来写，否则go mod 模式会有问题 ，建议你试试go mod 模式，开发非常方便

**Comment by zshorz** [comment]
@zseeker 我一直在用mod模式。我知道mod包名怎么写都行，但是短写在src模式下有问题，所以我关闭了issue
