### ISSUE TITLE
有没有websocket版本？

### ISSUE THREAD

**Issue by weicaijiang** [aceld/zinx#65]
请问下几时可以 弄一个websocket版本？

**Comment by ycg000344** [comment]
建议直接使用这个 [gorilla/websocket](https://github.com/gorilla/websocket)，这个zinx再实现websocket消息协议，不太合适。  :（

**Comment by ylp39** [comment]
可以把自己添加websocket，把socket替换成websocket。

**Comment by huguijian** [comment]
@weicaijiang   websocket 版本已出在wsserver分支上

**Comment by bournes** [comment]
有一个WEBSOCKET的DEMO就好了，比如SENDMSG等！！！

**Comment by aceld** [comment]
已支持
