### ISSUE TITLE
connmanager的ClearConn会导致死锁问题

### ISSUE THREAD

**Issue by EricLee0107** [aceld/zinx#72]
看到简书上一个人指出，但觉得修改方式不好，坐等作者大佬修复
Stop方法中会调用ConnManager的Remove方法，此时map锁还没有解锁

`//清除并停止所有连接
func (connMgr *ConnManager) ClearConn() {
	//保护共享资源Map 加写锁
	connMgr.connLock.Lock()
	defer connMgr.connLock.Unlock()

	//停止并删除全部的连接信息
	for connID, conn := range connMgr.connections {
		//停止
		conn.Stop()    // Stop方法中会调用ConnManager的Remove方法，此时map锁还没有解锁
		//删除
		delete(connMgr.connections, connID)
	}

	fmt.Println("Clear All Connections successfully: conn num = ", connMgr.Len())
}`

**Comment by WonderfulCat** [comment]
把ConnManager里的map改为sync.Map即可。

**Comment by aceld** [comment]
参见 https://github.com/aceld/zinx/issues/114
