### ISSUE TITLE
SetOnConnStop，设置的连接断开回调函数存在死锁问题

### ISSUE THREAD

**Issue by shangyexin** [aceld/zinx#80]
在使用```SetOnConnStop```设置连接断开的回调函数时，发现使用在回调函数中使用读取连接属性函数```conn.GetProperty```时，程序不会往下面执行。
调试代码时发现在```connection.go```文件中，加了写锁定，```c.Lock()```：
```go
//停止连接，结束当前连接状态M
func (c *Connection) Stop() {
	fmt.Println("Conn Stop()...ConnID = ", c.ConnID)
	//如果当前链接已经关闭
	c.Lock()
	defer c.Unlock()

	if c.isClosed == true {
		return
	}
	c.isClosed = true

	//如果用户注册了该链接的关闭回调业务，那么在此刻应该显示调用
	c.TcpServer.CallOnConnStop(c)

	// 关闭socket链接
	c.Conn.Close()
	//关闭Writer
	c.cancel()

	//将链接从连接管理器中删除
	c.TcpServer.GetConnMgr().Remove(c)

	//关闭该链接全部管道
	close(c.msgBuffChan)
}
```
而在在回调函数中使用的```GetProperty```里面也有读锁定，```c.RLock()```，所以就连接断开时没办法获取到连接属性。
```go
//获取链接属性
func (c *Connection) GetProperty(key string) (interface{}, error) {
	c.RLock()
	defer c.RUnlock()

	if value, ok := c.property[key]; ok {
		return value, nil
	} else {
		return nil, errors.New("no property found")
	}
}
```
不知道我理解的对不对，还是使用的方法有问题，望回复，谢谢！

**Comment by yilinershi** [comment]
发生了同样的问题，求解决方案

**Comment by yilinershi** [comment]
@shangyexin 这个问题你有解决么？遇到了同样的问题，你是怎么解决的？

**Comment by yilinershi** [comment]
> 在使用`SetOnConnStop`设置连接断开的回调函数时，发现使用在回调函数中使用读取连接属性函数`conn.GetProperty`时，程序不会往下面执行。
> 调试代码时发现在`connection.go`文件中，加了写锁定，`c.Lock()`：
> 
> ```go
> //停止连接，结束当前连接状态M
> func (c *Connection) Stop() {
> 	fmt.Println("Conn Stop()...ConnID = ", c.ConnID)
> 	//如果当前链接已经关闭
> 	c.Lock()
> 	defer c.Unlock()
> 
> 	if c.isClosed == true {
> 		return
> 	}
> 	c.isClosed = true
> 
> 	//如果用户注册了该链接的关闭回调业务，那么在此刻应该显示调用
> 	c.TcpServer.CallOnConnStop(c)
> 
> 	// 关闭socket链接
> 	c.Conn.Close()
> 	//关闭Writer
> 	c.cancel()
> 
> 	//将链接从连接管理器中删除
> 	c.TcpServer.GetConnMgr().Remove(c)
> 
> 	//关闭该链接全部管道
> 	close(c.msgBuffChan)
> }
> ```
> 
> 而在在回调函数中使用的`GetProperty`里面也有读锁定，`c.RLock()`，所以就连接断开时没办法获取到连接属性。
> 
> ```go
> //获取链接属性
> func (c *Connection) GetProperty(key string) (interface{}, error) {
> 	c.RLock()
> 	defer c.RUnlock()
> 
> 	if value, ok := c.property[key]; ok {
> 		return value, nil
> 	} else {
> 		return nil, errors.New("no property found")
> 	}
> }
> ```
> 
> 不知道我理解的对不对，还是使用的方法有问题，望回复，谢谢！

@shangyexin 这个问题你有解决么？遇到了同样的问题，你是怎么解决的？

**Comment by aceld** [comment]
@shangyexin @yilinershi 感谢两位发现问题，已经解决了，该问题是 @Zereker 在修正Connect线程安全bug的时候 [953c254](https://github.com/aceld/zinx/commit/953c254e5ccc09caa0fa712674a0c9a96addc36a) ，对Close加了锁，但是与property的锁重复了，导致死锁问题。 现在将两个锁分开就可以了，property 单独设立了一个属性的锁保护。
