### ISSUE TITLE
timerscheduler的CancelTimer，ids有可能越界

### ISSUE THREAD

**Issue by zhangxa** [aceld/zinx#85]
//删除timer
func (this *TimerScheduler) CancelTimer(tid uint32) {
	this.Lock()
	this.Unlock()
	//this.tw.RemoveTimer(tid)  这个方法无效
	//删除timerId
	var index = -1 //此处的0可修改为-1
	for i := 0; i < len(this.ids); i++ {
		if this.ids[i] == tid {
			index = i
		}
	}
	//此处加个判断
	if index > -1 {
		this.ids = append(this.ids[:index], this.ids[index+1:]...)
	}
	
}

**Comment by aceld** [comment]
感谢提供PR，已经修正。https://github.com/aceld/zinx/blob/master/ztimer/timerscheduler.go 

```go
//删除timer
func (this *TimerScheduler) CancelTimer(tid uint32) {
	this.Lock()
	this.Unlock()
	//this.tw.RemoveTimer(tid)  这个方法无效
	//删除timerId
	var index = -1
	for i := 0; i < len(this.ids); i++ {
		if this.ids[i] == tid {
			index = i
		}
	}

	if index > -1 {
		this.ids = append(this.ids[:index], this.ids[index+1:]...)
	}
}
```

**Comment by me10001** [comment]
//删除timer
func (this *TimerScheduler) CancelTimer(tid uint32) {
	this.Lock()
	defer this.Unlock()  //次数是不是少了  defer  
	//this.tw.RemoveTimer(tid)  这个方法无效
	//删除timerId
	var index = -1
	for i := 0; i < len(this.ids); i++ {
		if this.ids[i] == tid {
			index = i
		}
	}

	if index > -1 {
		this.ids = append(this.ids[:index], this.ids[index+1:]...)
	}
}

**Comment by me10001** [comment]
this.Unlock()   //此处是不是少了 defer  ?

//删除timer
func (this *TimerScheduler) CancelTimer(tid uint32) {
	this.Lock()
	this.Unlock()   //此处是不是少了 defer  ?
	//this.tw.RemoveTimer(tid)  这个方法无效
	//删除timerId
	var index = -1
	for i := 0; i < len(this.ids); i++ {
		if this.ids[i] == tid {
			index = i
		}
	}

	if index > -1 {
		this.ids = append(this.ids[:index], this.ids[index+1:]...)
	}
}

**Comment by zhangxa** [comment]
@me10001 @aceld 确实是少了defer

**Comment by aceld** [comment]
已更正。
