### ISSUE TITLE
是否可以授权给fork一个私有分支进行改动？

### ISSUE THREAD

**Issue by techmotive** [aceld/zinx#86]
你好，因为想使用zinx库，但是发现要做一些改动，比如要改打日志的方式和配置文件以及数据包解析，目前这些功能都是写死的，不能扩展，所以想fork一个私有分支进行改动，希望能得到授权，感谢！

**Comment by aceld** [comment]
完全可以，您可以加我的联系方式，我可以给您开通权限的。
